engine.cx/config/routes.rb
EngineCx::Application.routes.draw do
  resources :teams
  resources :invitations do
    member do
      get 'accept'
      get 'reject'
    end
  end

  devise_for :users

  match "/dashboard" => "dashboard#index", :as => :dashboard
  match "/team-room" => "team_room#index", :as => :team_room

  root :to => "index#index"

  

end

engine.cx/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :ensure_authenticated
  before_filter :find_invitations_for_current_user
  before_filter :find_team

  def index
=begin
    @games =Game.by(@current_user)
    @game_entries = []
    @teams = []
    @games.each do |game| # extract to models
      GameEntry.of_game(game).with_status("new").each do |entry|
         @game_entries << entry
      end
      GameEntry.of_game(game).with_status("accepted").each do |entry|
         @teams << entry.team
       end
    end
=end
  end

protected

  def find_invitations_for_current_user
    @invitations = Invitation.for current_user
  end

  def find_team
    @team = current_user.team if current_user.team
  end
end

engine.cx/app/views/dashboard/_my_team.html.erb
<fieldset>
  <legend>
    Моя команда
  </legend>
  
  <% unless current_user.member_of_any_team? %>

    <p>
      Вы не состоите ни в одной из команд
    </p>

    <p>
      <%= link_to "Создать команду", new_team_path %>
    </p>
    
    <br />

    <% @invitations.each do |invitation| %>
      <p>Вас пригласили в команду <%= invitation.to_team.name %>
        <em><%= link_to "(принять)", { :controller => "invitations", :action => "accept", :id => invitation.id } , :id => "accept-invitation-#{invitation.id}" %></em>
        <em><%= link_to "(отказаться)", { :controller => "invitations", :action => "reject", :id => invitation.id }, :id => "reject-invitation-#{invitation.id}" %></em>
      </p>
    <% end %>

  <% else %>

    <p>
      <%= current_user.captain? ? "Вы - капитан команды" : "Вы состоите в команде" %> <strong><%= current_user.team.name %></strong>
    </p>
    
    <p>
      <%= link_to "Перейти в комнату команды", team_room_url %>
    </p>

  <% end %>
</fieldset>

engine.cx/app/views/dashboard/index.html.erb
<p>
   Вы <%= @current_user.nickname %>
</p>

<p>
   <%= render 'my_team' %>
</p>

<p>
   <%#= partial 'my_games' %>
</p>

<p>
  <%#= partial 'shared/current_games' %>
</p>

<p>
  <%#= partial 'dashboard/coming_games' %>
</p>

<p>
  <%#= partial 'dashboard/finished_games' %>
</p>

<p>
  <%#= partial 'games/game_entries', :game_entries => @game_entries  %>
</p>

<p>
  <%#= partial 'games/teams', :teams => @teams  %>
</p>