config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do 
    get '/signup', to: 'devise/registrations#new', as: :signup
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :users, :only => [:index, :show] do
    resources :games

    member do
      post 'leave_team'
      post 'set_access_admin'
      post 'set_access_organizer'
      post 'set_access_player'
      patch 'update_data'
      put 'update_data'
      get 'edit_data'
    end
  end

  resources :teams do
    member do
      post 'set_captain/:user_id', :action => 'set_captain', :as => 'set_captain'
    end
  end

  resources :invitations do
    member do
      post 'accept'
      post 'reject'
    end
  end

  resources :team_applications do
    member do
      post 'accept'
      post 'reject'
    end
  end

  resources :games do
    resources :levels do
      resources :hints
      resources :questions do
        resources :answers
      end

      member do
        get 'move_up'
        get 'move_down'
      end
    end

    member do
      get 'end_game'
      get 'start_test'
      get 'finish_test'
    end
  end
 
  get '/play_as/:game_id/:team_id', to: 'game_passings#play_as_team', as: :play_as_team
  get '/play/:game_id', to: 'game_passings#show_current_level', as: :show_current_level
  post '/play/:game_id', to: 'game_passings#post_answer', as: :post_answer
  post '/play/:game_id/exit_game', to: 'game_passings#exit_game', as: :exit_game

  get '/user_list', to: 'users#list', as: :user_list

  get '/stats', to: 'game_stats#index', as: :stats
  get '/stats/:game_id/show', to: 'game_stats#show', as: :game_stats
  get '/stats/:game_id/adjustments/:team_id', to: 'game_stats#adjustments', as: :game_stats_adjustments
  get '/stats/:game_id/finish', to: 'game_stats#finish', as: :game_finish
  post '/stats/:game_id/adjustments/:team_id/add', to: 'game_stats#add_adjustment', as: :add_game_stats_adjustment
  delete '/stats/adjustments/:adjustment_id/remove', to: 'game_stats#remove_adjustment', as: :remove_game_stats_adjustment
  post '/stats/:game_id/publish', to: 'game_stats#publish', as: :publish_stats
  post '/stats/:game_id/takedown', to: 'game_stats#takedown', as: :takedown_stats

  get '/ratings', to: 'ratings#index', as: :ratings
  get '/logs/livechannel/:game_id', to: 'logs#show_live_channel', as: :show_live_channel # прямой эфир
  get '/logs/level/:game_id/:team_id', to: 'logs#show_level_log', as: :show_level_log # лог по уровню
  get '/logs/game/:game_id/:team_id', to: 'logs#show_game_log', as: :show_game_log # лог по игре
  get '/logs/full/:game_id', to: 'logs#show_full_log', as: :show_full_log # полный лог по игре
  
  get '/game_entries/new/:game_id/:team_id', to: 'game_entries#new', as: :new_game_entry # отправка заявки
  get '/game_entries/recall/:id', to: 'game_entries#recall', as: :recall_game_entry # отзыв заявки
  get '/game_entries/cancel/:id', to: 'game_entries#cancel', as: :cancel_game_entry # отмен заявки
  get '/game_entries/reopen/:id', to: 'game_entries#reopen', as: :reopen_game_entry # заново заявка
  get '/game_entries/accept/:id', to: 'game_entries#accept', as: :accept_game_entry # заявка принята
  get '/game_entries/reject/:id', to: 'game_entries#reject', as: :reject_game_entry # заявка отказана

  post '/upload/image', to: 'upload#image', as: :upload_image
  post '/upload/file', to: 'upload#file', as: :upload_file

  get '/dashboard', to: 'dashboard#index', as: :dashboard
  get '/send_msg', to: 'dashboard#send_msg', as: :send_msg
  get '/settings', to: 'settings#index', as: :settings
  post '/settings/update', to: 'settings#update', as: :update_settings

  root to: 'index#index', as: :index_page
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hint.rb
# -*- encoding : utf-8 -*-
class Hint < ApplicationRecord
  belongs_to :level
  has_many :logs, as: :linkable

  def penalty_time_in_minutes
    self.penalty_time.nil? ? nil : self.penalty_time / 60
  end

  def penalty_time_in_minutes=(value)
    self.penalty_time = value.to_i * 60
  end  

  def delay_in_minutes
    self.delay.nil? ? nil : self.delay / 60
  end

  def delay_in_minutes=(value)
    self.delay = value.to_i * 60
  end

  def ready_to_show?(current_level_entered_at)
    seconds_passed = Time.now - current_level_entered_at
    seconds_passed >= self.delay and !self.is_spoiler?
  end

  def available_in(current_level_entered_at)
    (current_level_entered_at - Time.now).to_i + self.delay
  end

  def availability_date(current_level_entered_at)
    Time.at((current_level_entered_at).to_i + self.delay)
  end

  def is_opened_by?(code)
      self.access_code.mb_chars.upcase.to_s == code.mb_chars.upcase.to_s
  end

  def is_spoiler? ()
    !self.access_code.blank?
  end
end

app/controllers/hints_controller.rb
# -*- encoding : utf-8 -*-
class HintsController < ApplicationController
  before_action :find_level
  before_action :find_game
  before_action :build_hint, :only => [:new, :create]
  before_action :find_hint, :only => [:edit, :update, :destroy]

  before_action :ensure_author
  before_action :ensure_game_was_not_started, :only => [:new, :create, :edit, :update]  

  def new
    render
  end

  def create
    if @hint.save
      redirect_to [@game, @level]
    else
      render :new
    end
  end

  def edit
    render
  end

  def update
    if @hint.update(hint_params)
      redirect_to [@level.game, @level]
    else
      render :edit
    end
  end

  def destroy
    @hint.destroy
    redirect_to [@level.game, @level]
  end

protected

  def hint_params
    params[:hint].permit(:text, :delay_in_minutes, :access_code, :penalty_time_in_minutes) unless params[:hint].nil?
  end

  def build_hint
    @hint = Hint.new(hint_params)
    @hint.level = @level
  end

  def find_level
    @level = Level.find(params[:level_id])
  end

  def find_game
    @game = @level.game
  end

  def find_hint
    @hint = Hint.find(params[:id])
  end
end

app/views/hints/_form.html.erb
<div class="row">
  <%= f.label :text, t(:text, scope: [:activerecord, :attributes, :hint]) %>
  <%= f.text_area :text, data: { :wysiwyg => true }  %>
</div>
<div class="row">
  <%= f.label :access_code, t(:access_code, scope: [:activerecord, :attributes, :hint]) %>
  <%= f.text_field :access_code %>
</div>
<div class="row">
  <%= f.label :delay_in_minutes, t(:delay_in_minutes, scope: [:activerecord, :attributes, :hint]) %>
  <%= f.text_field :delay_in_minutes, :type => :number %>
  <span>минут</span>
</div>
<div class="row">
  <%= f.label :penalty_time_in_minutes, t(:penalty_time_in_minutes, scope: [:activerecord, :attributes, :hint]) %>
  <%= f.text_field :penalty_time_in_minutes, :type => :number %>
  <span>минут</span>
</div>

<style type="text/css">
#hint_delay_in_minutes {
    width: 100px;
    display: inline-block;
}
#hint_penalty_time_in_minutes {
    width: 100px;
    display: inline-block;
}
</style>

app/views/hints/_list.html.erb
<% if hints.empty? %>
  <p>Подсказок нет</p>
<% else %>
  <table class="hints-list">
    <thead>
    <tr>
      <th>Время до подсказки<br>или код спойлера</th>
      <th>Текст</th>
      <th>Действия</th>
    </tr>
    </thead>
    <tbody>
    <% hints.each do |hint| %>
        <tr class="hint-item">
          <% if hint.delay and hint.delay > 0 %>
          <td class="hint-delay">
            <p class="delay">Через <strong><%= link_to hint.delay_in_minutes, [:edit, hint.level.game, hint.level, hint] %></strong> минут</p>
            <% if hint.penalty_time and hint.penalty_time > 0 %>
              <p class="penalty">(штраф: <%= hint.penalty_time_in_minutes %> минут)</p>
            <% end %>
          </td>
          <% elsif hint.access_code %>
          <td class="hint-access_code">
            <p class="code"><%= hint.access_code %></p>
            <% if hint.penalty_time and hint.penalty_time > 0 %>
              <p class="penalty">(штраф: <%= hint.penalty_time_in_minutes %> минут)</p>
            <% end %>
          </td>
          <% end %>
          <td class="hint-text fr-view">
            <%= hint.text.html_safe %>
          </td>
          <td class="hint-actions">
            <%= link_to [:edit, hint.level.game, hint.level, hint] do %>
              <i class="far fa-edit"></i>
            <% end %>
            <%= link_to [hint.level.game, hint.level, hint], :method => :delete, :data => {:confirm => "Вы уверены, что собираетесь удалить подсказку?"} do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/hints/edit.html.erb
<div class="hint-edit-page">
<h4 class="heading">
  <span>Редактирование подсказки к заданию "<%= link_to @level.name, [@game, @level] %>" игры "<%= link_to @game.name,@game %>"</span>
</h4>

<%= error_messages_for @hint, :header => "<h2>Ошибка</h2>" %>

<%= form_for [@game, @level, @hint], :action => game_level_hints_path(@game, @level) do |f| %>

  <%= render 'form', :hint => @hint, :f => f %>

  <div class="row form-actions">
      <%= f.submit t(:update, scope: [:activerecord, :attributes, :hint]) %>
      <%= link_to "(вернуться)", [@hint.level.game, @hint.level] %>
  </div>
<% end %>
</div>

app/views/hints/new.html.erb
<div class="hint-add-page">
<h4 class="heading">
  <span>Новая подсказка для задания "<%= link_to @level.name, [@game, @level] %>" игры "<%= link_to @game.name, @game %>"</span>
</h4>

<br />

<%= error_messages_for @hint, :header => "<h2>Ошибка</h2>" %>

<%= form_for [@game, @level, @hint], :action => game_level_hints_path(@game, @level) do |f| %>

  <%= render 'form', :hint => @hint, :f => f %>

  <div class="row form-actions">
    <%= f.submit t(:submit, scope: [:activerecord, :attributes, :hint]) %>
    <%= link_to "(вернуться)", [@hint.level.game, @hint.level] %>
  </div>
<% end %>
</div>