config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do 
    get '/signup', to: 'devise/registrations#new', as: :signup
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :users, :only => [:index, :show] do
    resources :games

    member do
      post 'leave_team'
      post 'set_access_admin'
      post 'set_access_organizer'
      post 'set_access_player'
      patch 'update_data'
      put 'update_data'
      get 'edit_data'
    end
  end

  resources :teams do
    member do
      post 'set_captain/:user_id', :action => 'set_captain', :as => 'set_captain'
    end
  end

  resources :invitations do
    member do
      post 'accept'
      post 'reject'
    end
  end

  resources :team_applications do
    member do
      post 'accept'
      post 'reject'
    end
  end

  resources :games do
    resources :levels do
      resources :hints
      resources :questions do
        resources :answers
      end

      member do
        get 'move_up'
        get 'move_down'
      end
    end

    member do
      get 'end_game'
      get 'start_test'
      get 'finish_test'
    end
  end
 
  get '/play_as/:game_id/:team_id', to: 'game_passings#play_as_team', as: :play_as_team
  get '/play/:game_id', to: 'game_passings#show_current_level', as: :show_current_level
  post '/play/:game_id', to: 'game_passings#post_answer', as: :post_answer
  post '/play/:game_id/exit_game', to: 'game_passings#exit_game', as: :exit_game

  get '/user_list', to: 'users#list', as: :user_list

  get '/stats', to: 'game_stats#index', as: :stats
  get '/stats/:game_id/show', to: 'game_stats#show', as: :game_stats
  get '/stats/:game_id/adjustments/:team_id', to: 'game_stats#adjustments', as: :game_stats_adjustments
  get '/stats/:game_id/finish', to: 'game_stats#finish', as: :game_finish
  post '/stats/:game_id/adjustments/:team_id/add', to: 'game_stats#add_adjustment', as: :add_game_stats_adjustment
  delete '/stats/adjustments/:adjustment_id/remove', to: 'game_stats#remove_adjustment', as: :remove_game_stats_adjustment
  post '/stats/:game_id/publish', to: 'game_stats#publish', as: :publish_stats
  post '/stats/:game_id/takedown', to: 'game_stats#takedown', as: :takedown_stats

  get '/ratings', to: 'ratings#index', as: :ratings
  get '/logs/livechannel/:game_id', to: 'logs#show_live_channel', as: :show_live_channel # прямой эфир
  get '/logs/level/:game_id/:team_id', to: 'logs#show_level_log', as: :show_level_log # лог по уровню
  get '/logs/game/:game_id/:team_id', to: 'logs#show_game_log', as: :show_game_log # лог по игре
  get '/logs/full/:game_id', to: 'logs#show_full_log', as: :show_full_log # полный лог по игре
  
  get '/game_entries/new/:game_id/:team_id', to: 'game_entries#new', as: :new_game_entry # отправка заявки
  get '/game_entries/recall/:id', to: 'game_entries#recall', as: :recall_game_entry # отзыв заявки
  get '/game_entries/cancel/:id', to: 'game_entries#cancel', as: :cancel_game_entry # отмен заявки
  get '/game_entries/reopen/:id', to: 'game_entries#reopen', as: :reopen_game_entry # заново заявка
  get '/game_entries/accept/:id', to: 'game_entries#accept', as: :accept_game_entry # заявка принята
  get '/game_entries/reject/:id', to: 'game_entries#reject', as: :reject_game_entry # заявка отказана

  post '/upload/image', to: 'upload#image', as: :upload_image
  post '/upload/file', to: 'upload#file', as: :upload_file

  get '/dashboard', to: 'dashboard#index', as: :dashboard
  get '/send_msg', to: 'dashboard#send_msg', as: :send_msg
  get '/settings', to: 'settings#index', as: :settings
  post '/settings/update', to: 'settings#update', as: :update_settings

  root to: 'index#index', as: :index_page
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_current_games.html.erb
<% if current_user %>
  <% unless Game.started.empty? %>
    <fieldset>
      <legend>
        Текущие игры домена
      </legend>

      <% (Game.active(current_user)).each do |game| %>
        <div id="game-<%= game.id %>">
          <% unless game.is_testing? %>
          Началась игра "<%= link_to game.name, game %>" |
              <% if current_user.team.finished?(game) or game.created_by?(current_user) %>
                <%= link_to "Посмотреть результаты", game_stats_path(game) %>
              <% else %>
                <% if game.levels && game.levels.count > 0 %>
                  <%  @game_entry = GameEntry.of(@team,game) %>
                  <%= render 'shared/current_games_status', :game_entry => @game_entry, :game => game %>
                <% else %>
                  Игра не содержит заданий
                <% end %>
              <% end %>
           <% end %>
        </div>
      <% end %>
    </fieldset>
  <% end %>
<% end %>

app/views/shared/_current_games_status.html.erb
<% if game_entry %>
  <% case game_entry.status %>
  <% when "accepted" %>
    <%= link_to "Играть!", :show_current_level, :game_id => game.id %>
  <% else %>
    Вы не зарегистрированы
  <% end %>
<% end %>

app/views/shared/_flashes.erb
<% unless flash.empty? %>
<div class="flash-messages">
  <% flash.each do |key, message| %>
    <div class="message <%= key %>" data-type="<%= key %>">
      <p class="content"><%= message %></p>
    </div>
  <% end %>
</div>
<% end %>

app/views/shared/_game_entry_controls.html.erb
<% if game_entry %>
  <% case game_entry.status %>
  <% when "new" %>
    Заявка подана
    <%= link_to "Отозвать", recall_game_entry_path(game_entry.id) %>
  <% when "accepted" %> Вы зарегистрированы
    <%= link_to "Отказаться", cancel_game_entry_path(game_entry.id) %>
  <% when "recalled", "rejected", "canceled", nil %>
    <% if game.requested_teams_number < game.max_team_number %>
      <%= link_to "Подать заявку на регистрацию заново", reopen_game_entry_path(game_entry.id) %>
    <% else %>
      Вы не можете зарегистрироваться так как превышено количество участников
    <% end %>
  <% end %>
<% else %>
  <% if game.requested_teams_number >= game.max_team_number %>
    Вы не можете зарегистрироваться так как превышено количество участников
  <% elsif game.registration_deadline and game.registration_deadline <= Time.now %>
    Вы не можете зарегистрироваться, так как опоздали на игру
  <% else %>
    <%= link_to "Подать заявку на регистрацию", new_game_entry_path(game.id, team.id) %>
  <% end %>
<% end %>