config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do 
    get '/signup', to: 'devise/registrations#new', as: :signup
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :users, :only => [:index, :show] do
    resources :games

    member do
      post 'leave_team'
      post 'set_access_admin'
      post 'set_access_organizer'
      post 'set_access_player'
      patch 'update_data'
      put 'update_data'
      get 'edit_data'
    end
  end

  resources :teams do
    member do
      post 'set_captain/:user_id', :action => 'set_captain', :as => 'set_captain'
    end
  end

  resources :invitations do
    member do
      post 'accept'
      post 'reject'
    end
  end

  resources :team_applications do
    member do
      post 'accept'
      post 'reject'
    end
  end

  resources :games do
    resources :levels do
      resources :hints
      resources :questions do
        resources :answers
      end

      member do
        get 'move_up'
        get 'move_down'
      end
    end

    member do
      get 'end_game'
      get 'start_test'
      get 'finish_test'
    end
  end
 
  get '/play_as/:game_id/:team_id', to: 'game_passings#play_as_team', as: :play_as_team
  get '/play/:game_id', to: 'game_passings#show_current_level', as: :show_current_level
  post '/play/:game_id', to: 'game_passings#post_answer', as: :post_answer
  post '/play/:game_id/exit_game', to: 'game_passings#exit_game', as: :exit_game

  get '/user_list', to: 'users#list', as: :user_list

  get '/stats', to: 'game_stats#index', as: :stats
  get '/stats/:game_id/show', to: 'game_stats#show', as: :game_stats
  get '/stats/:game_id/adjustments/:team_id', to: 'game_stats#adjustments', as: :game_stats_adjustments
  get '/stats/:game_id/finish', to: 'game_stats#finish', as: :game_finish
  post '/stats/:game_id/adjustments/:team_id/add', to: 'game_stats#add_adjustment', as: :add_game_stats_adjustment
  delete '/stats/adjustments/:adjustment_id/remove', to: 'game_stats#remove_adjustment', as: :remove_game_stats_adjustment
  post '/stats/:game_id/publish', to: 'game_stats#publish', as: :publish_stats
  post '/stats/:game_id/takedown', to: 'game_stats#takedown', as: :takedown_stats

  get '/ratings', to: 'ratings#index', as: :ratings
  get '/logs/livechannel/:game_id', to: 'logs#show_live_channel', as: :show_live_channel # прямой эфир
  get '/logs/level/:game_id/:team_id', to: 'logs#show_level_log', as: :show_level_log # лог по уровню
  get '/logs/game/:game_id/:team_id', to: 'logs#show_game_log', as: :show_game_log # лог по игре
  get '/logs/full/:game_id', to: 'logs#show_full_log', as: :show_full_log # полный лог по игре
  
  get '/game_entries/new/:game_id/:team_id', to: 'game_entries#new', as: :new_game_entry # отправка заявки
  get '/game_entries/recall/:id', to: 'game_entries#recall', as: :recall_game_entry # отзыв заявки
  get '/game_entries/cancel/:id', to: 'game_entries#cancel', as: :cancel_game_entry # отмен заявки
  get '/game_entries/reopen/:id', to: 'game_entries#reopen', as: :reopen_game_entry # заново заявка
  get '/game_entries/accept/:id', to: 'game_entries#accept', as: :accept_game_entry # заявка принята
  get '/game_entries/reject/:id', to: 'game_entries#reject', as: :reject_game_entry # заявка отказана

  post '/upload/image', to: 'upload#image', as: :upload_image
  post '/upload/file', to: 'upload#file', as: :upload_file

  get '/dashboard', to: 'dashboard#index', as: :dashboard
  get '/send_msg', to: 'dashboard#send_msg', as: :send_msg
  get '/settings', to: 'settings#index', as: :settings
  post '/settings/update', to: 'settings#update', as: :update_settings

  root to: 'index#index', as: :index_page
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/game_stats_controller.rb
class GameStatsController < ApplicationController
  before_action :find_game, :except => [:index, :remove_adjustment]
  before_action :find_team, :only => [:adjustments, :add_adjustment]
  before_action :find_game_passing, :only => [:adjustments, :add_adjustment]
  before_action :find_adjustment, :only => [:remove_adjustment]
  before_action :find_game_passings, :except => [:index]
  before_action :build_adjustment, :only => [:adjustments, :add_adjustment]
  before_action :ensure_team_member, :only => [:finish]
  before_action :ensure_author, :only => [:publish, :takedown]
  before_action :ensure_author_if_not_published, :only => [:show]

  def index
    @games = Game.results_available_for(current_user)
    render
  end

  def show
    render
  end

  def add_adjustment
    @adjustment.save
    redirect_back :fallback_location => game_stats_adjustments_path(@game, @team)
  end

  def remove_adjustment
    @game = @adjustment.game_passing.game
    @team = @adjustment.game_passing.team
    @adjustment.destroy
    redirect_back :fallback_location => game_stats_adjustments_path(@game, @team)
  end

  def adjustments
    render
  end

  def finish
    render
  end

  def publish
    GameInteractors::Publish.call({:game => @game, :user => current_user})
    redirect_back :fallback_location => game_stats_path(@game)
  end

  def takedown
    GameInteractors::Takedown.call({:game => @game, :user => current_user})
    redirect_back :fallback_location => game_stats_path(@game)
  end

  protected

  def render_sidebar?
    action_name === 'index' || action_name === 'finish'
  end

  private

  def adjustment_params
    if params[:adjustment].nil?
      return nil
    end

    params[:adjustment][:adjustment] = params[:adjustment][:adjustment].to_i.abs

    if params[:adjustment][:type] == "penalty"
      params[:adjustment][:adjustment] = params[:adjustment][:adjustment] * -1
    end

    params[:adjustment].permit(:adjustment, :reason)
  end

  def build_adjustment
    @adjustment = PassingAdjustment.new(adjustment_params)
    @adjustment.game_passing = @game_passing
    @adjustment
  end

  def find_game
    @game = Game.find params[:game_id]
  end

  def find_team
    @team = Team.friendly.find params[:team_id]
  end

  def find_game_by_id
    @game = Game.find params[:id]
  end

  def find_adjustment
    @adjustment = PassingAdjustment.find params[:adjustment_id]
  end

  def find_game_passing
    @game_passing = GamePassing.of(@team, @game)
  end

  def find_game_passings
    @game_passings = GamePassing.of_game(@game)
  end

  def ensure_author_if_not_published
    unless @game.published?
      ensure_author
    end
  end
end

app/helpers/game_stats_helper.rb
module GameStatsHelper
end

app/views/game_stats/adjustments.erb
<div class="game-stats-page">
  <h3 class="heading">
    <span>Список штрафов и бонусов команды &laquo;<%= link_to @team.name, @team %>&raquo;</span>
    <%= link_to "Назад к статистике", game_stats_path(@game), :class => 'right-link' %>
  </h3>
  <a data-toggle="new-adjustment-dropdown">Добавить</a>
  <div class="dropdown-pane" id="new-adjustment-dropdown" data-dropdown data-auto-focus="true" data-close-on-click="true" data-v-offset="8">
    <%= form_for :adjustment, :url => add_game_stats_adjustment_path(@game, @team), :data => { "model": "adjustment" } do |f| %>
      <div class="row">
        <%= f.radio_button :type, :bonus %>
        <%= f.label :type, t(:type_bonus, scope: [:activerecord, :attributes, :adjustment]), :value => :bonus, :class => 'inline' %>
        <span class="inline separator">/</span>
        <%= f.radio_button :type, :penalty %>
        <%= f.label :type, t(:type_penalty, scope: [:activerecord, :attributes, :adjustment]), :value => :penalty, :class => 'inline' %>
      </div>
      <div class="row">
        <%= f.label :adjustment, t(:adjustment, scope: [:activerecord, :attributes, :adjustment]) %>
        <%= f.text_field :adjustment %>
      </div>
      <div class="row">
        <%= f.label :reason, t(:reason, scope: [:activerecord, :attributes, :adjustment]) %>
        <%= f.text_field :reason %>
      </div>
      <div class="row form-actions">
        <%= f.submit t(:submit, scope: [:activerecord, :attributes, :adjustment]) %>
      </div>
    <% end %>
  </div>
  <%= cell(GameStatsPage::AdjustmentsTable, @game_passing) %>
</div>

app/views/game_stats/finish.erb
<div class="game-finish-page">
  <h2 class="heading"><span>Поздравляем, вы закончили игру!</span></h2>
<% if @game.is_testing? %>
  <br/>
  <%= link_to "Завершить тестирование", finish_test_game_path(@game.id) %>
<% end %>

</div>

app/views/game_stats/index.erb
<div class="stats-index-page">
  <h2 class="heading"><span>Результаты прошедших игр</span></h2>
  <% unless @games.empty? %>
    <div class="games-listing">
    <% @games.each do |game| %>
      <%= cell(GameStatsPage::GameItem, game) %>
    <% end %>
    </div>
  <% else %>
    <div class="empty-list">
      Здесь пока пусто
    </div>
  <% end %>
</div>

app/views/game_stats/show.erb
<div class="game-stats-page">
  <%= cell(GameStatsPage::Heading, @game) %>
  <%= cell(GameStatsPage::Table, @game) %>
  <%= cell(GameStatsPage::LevelListing, @game) %>
</div>